### ISSUE TITLE
crashes (in gaming and desktop mode)

### ISSUE THREAD

**Issue by letraitplat** [ddotthomas/SteamDeck_SD_Card_Scanner#2]
hello
I found your project very interesting and decided to give it a try
downloaded latest release, added as non steam game in desktop mode
when I hit play, both in desktop or gaming mode, nothing happens, I directly go back to steam's UI
Any help welcome, thanks :)

**Comment by greengeckoz** [comment]
Hey, I just now saw this; somehow I missed it. I'll look into it and see if any recent updates broke it. 

Edit: In the meantime, if you get the chance, could you try running the app through the Konsole/Terminal in desktop mode and see what output is shown. There might be an error message explaining what's happening.

**Comment by greengeckoz** [comment]
I think I know what happened. The binary is marked as executable in the permissions but after being downloaded from GitHub the permissions are reset. Try opening the binary's properties in desktop mode, go to Permissions and check the 'Is Executable' box, let me know if that fixes it.

**Comment by letraitplat** [comment]
Thanks for checking this out. Testing in a few and will give you results.
Looking forward to be able to use that tool as it serves what I thought was
quite a unique use case that I had, but seems I'm not alone ;)

**Comment by greengeckoz** [comment]
Yeah, I'm new to programming so you'll probably be able to tell that right away. Right now I'm going to work on a Settings page so you can customize the name the card and maybe be able to manually set a card non-steam library folders location.

**Comment by letraitplat** [comment]
Do you have a duplicate in-between cards highlighter feature planned ? That
would come in handy !

**Comment by letraitplat** [comment]
Just to let you know : doing what you suggested (desktop mode > edit properties > set as executable) worked right away. Both in desktop mode (it asked for confirmation if I wanted to execute it, I said yes and not to ask anymore), but also from gaming mode.


If you don't mind, do you have a place where we can add some feature requests ?


In any case, thanks for the hard work, this is going to be super useful ! can't wait to see future upgrades to this :)

**Comment by greengeckoz** [comment]
You can just suggest them here, I'm the only developer. Otherwise I think the 'Issues' section in github that we're in now is the correct place. If it were me I would just mark it as [Feature Request] in the title. 

But yeah, the idea to check if there's any duplicate between the cards and highlight them is a good idea. I'll try to work on that.

**Comment by letraitplat** [comment]
done ! 
thanks a lot
I'm no programmer at all either but if I can be of any help, I would love to.
I listed some features, the only one I'm unsure is a feature or a bug, is about the list being stuck even if content overflows. No scroll whatsoever, and mouse cursor stops at the middle of the screen, won't go to the far right allowing to reach the scrollbar.

Thanks again for the work :)
