### ISSUE TITLE
SD Root may be dynamic.

### ISSUE THREAD

**Issue by jcc10** [ddotthomas/SteamDeck_SD_Card_Scanner#7]
When mounting my SD cards it's now showing up under `/run/media/deck/[some kind of UUID?]`

This causes the app to not function.

It may be best for the app to scan `/run/media/*` for the `steamapps` folder and have a `cardname.txt` file with one line being the card's name. (or just generate a name from the path?)

anyway, this may just be from the preview channel or it may not, however it would allow for multiple libraries to be tracked at the same time. (For docked / USB drive situations.)

**Comment by greengeckoz** [comment]
I'll have to look into that, thanks for bringing it up

**Comment by greengeckoz** [comment]
The issue should be fixed with the updates from #8
